### ISSUE TITLE
I couldn't run the python file.

### ISSUE THREAD

**Issue by tinywifi** [k0rnh0li0/GriefBuddy#1]
![image](https://user-images.githubusercontent.com/65711396/139577163-3ee3e9c5-6987-403e-b8c7-d8b54b353532.png)

**Comment by k0rnh0li0** [comment]
What did you put in your config.json?
You're most likely getting this error because you entered the wrong API key. Make sure you copy it correctly from https://account.shodan.io/

**Comment by getgle** [comment]
close this issue it isn't our problem
